### PR TITLE
version 4

### PR DESCRIPTION
**Pull request by MartkCz**
- [x] Create invoice pdf from svg (new repository for svg to pdf)
- [x] Auto-greyscale
- [x] Remove calculators and formatters (fixed string values)
- [x] Simplify data classes
- [x] PHP 8.0
- [x] Replace template
- [x] Add old template?

### CODE REVIEW

**Comment by f3l1x** [comment]
How is it going?

**Comment by MartkCz** [comment]
it was a long time ago, I have to look at it again :)

**Comment by MartkCz** [comment]
@f3l1x I'm done

**Comment by jozefrebjak** [comment]
@MartkCz It looks nice. When it will be this version available ?

**Pull request merged**
