### PR TITLE
v3.0.0 fix - ITemplate constructor arguments

### PR DESCRIPTION
**Pull request by peterkracik**
Using a Formatter interface rather than class for the template constructor arguments

### CODE REVIEW

**Comment by peterkracik** [comment]
Hi,
would it be possible to merge my change to the v3.0.0?

thanks

**Comment by f3l1x** [comment]
Please change PR to master branch.

**Comment by f3l1x** [comment]
ping @peterkracik

**Comment by peterkracik** [comment]
@f3l1x I did the modification on the current stable version (3.0.0), which is I believe the fix/ci. The file on master branch is already changed and also it contains the edit I requested (using IRenderer instead of Renderer)

**Comment by f3l1x** [comment]
Sorry, I don't get it, **master** branch is mandatory. fix/ci was left-over from PR (https://github.com/contributte/invoice/pull/18).

**Comment by f3l1x** [comment]
Constructor was removed from ITemplate (https://github.com/contributte/invoice/commit/0fcf6bb9e262f594c6ec72ce56a63a42077362ee).

**Pull request closed without merging**
